# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualitymd" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "29759020cd3b3a3158d131a69a5e6f19a8ab71d48155c4ada770330ad86843b3"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f40b00ddc0f4f4c807b32eb73d97a101ab97a691e334ccdfe3a1fbd6f87c346"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9ddca3a4b0a292632e5f40259cb022a8f4898b97a304496e61c8942118580fb"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c6e23771ef5cd0a87382bf370a850082260dcfd7e40cc74af35d1ade9b6e475"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_linux_arm64.tar.gz"
    end
  end

  name "qualitymd"
  desc "Evaluate QUALITY.md specifications"
  homepage "https://github.com/qualitymd/quality.md"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualitymd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualitymd"]
    end
  end

  # No zap stanza required

end
