# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualitymd" do
  version "0.25.1"

  on_macos do
    on_intel do
      sha256 "ebc3d04766209b5a2f61ce65eef49a93f1fcd7094c446b5247d4bca4e01bc65a"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b52c6d60a36e7e964d58cc8546d1d5349a25fb2d643b7e8ff2484c6c575fb63a"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d6e6a8d51c1a66c38eab0a0cba62514b924178693af74d87fe47c4d414f46a0"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ffe987ea142e5274dd565ad909c4e42664483d7417e961d312fd5ab6906aa24"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_linux_arm64.tar.gz"
    end
  end

  name "qualitymd"
  desc "Evaluate QUALITY.md specifications"
  homepage "https://github.com/qualitymd/quality.md"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualitymd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualitymd"]
    end
  end

  # No zap stanza required

end
