# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualitymd" do
  version "0.28.0"

  on_macos do
    on_intel do
      sha256 "80b178c45a3b028a6c972727c2851eb317841f8790dd314c47ea66e86b53cd69"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e335fabc139332b90b1025c87889a3f5bfdf3931abac98121026c239b9ea63de"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b60c5483382866725e7a101407519f4870653b5111250ab3da8868c1195f4177"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "71be00d18cbd04e672077677c8967541fc0738f2bbf7a967c82bf767dca9c0e2"
      url "https://github.com/qualitymd/quality.md/releases/download/v#{version}/qualitymd_linux_arm64.tar.gz"
    end
  end

  name "qualitymd"
  desc "Evaluate QUALITY.md specifications"
  homepage "https://github.com/qualitymd/quality.md"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualitymd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualitymd"]
    end
  end

  # No zap stanza required

end
